### ISSUE TITLE
refactor registerPlugin to onSchemaReady(input_schema, output_schema)

### ISSUE THREAD

**Issue by zharikovpro** [zharikovpro/react-plugin#11]

**Comment by zharikovpro** [comment]
`onSchemaReady` is a better word than `loaded`. It's like on document ready. except that we may form schema dynamically without "loading" it.

**Comment by nikolay-govorov** [comment]
What should be in inputSchema?

**Comment by zharikovpro** [comment]
For input plugins input schema is the same as output. I.e. TextInput may have an optional current value after page load.

**Comment by nikolay-govorov** [comment]
And the function onSchemaReady is a required parameter?

**Comment by zharikovpro** [comment]
No, callbacks cannot be required. They are always optional.
